### ISSUE TITLE
I am getting following error termination. Kindly suggest.

### ISSUE THREAD

**Issue by nityasagarjena** [eveshower/VASPbandplot#1]
sh band.sh
reading EIGENVAL...
number of valent electrons=18
number of k points= 300
number of bands= 16
E-fermi= = =  (from OUTCAR)
x range= 30:300
y range= -10:5

gnuplot> set terminal svg size 380,880 enhanced font 'Times-Roman,15'
                                  ^
         "gnuband2.plt", line 8: invalid expression

**Comment by yyyu200** [comment]
I guess it is with the gnuplot terminal type, some of the format are not installed, in this case, svg terminal. You may uncomment other terminal types such as `set terminal png size 380,880 ` . 

At current stage, you should modify the code according to your situation.
